'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const serverUrl = document.querySelector('meta[name="omr-server-url"]')?.content.trim() || location.origin;
  const SAVE = 'one-more-relic:v11-meta';
  const skins = [
    {id:'moss',name:'Moss Wanderer',color:'#cce6a2',unlock:'Ready from the first run',owned:true},
    {id:'ember',name:'Emberbound',color:'#ee9b6b',unlock:'Beat a boss',owned:false},
    {id:'frost',name:'Frost Wisp',color:'#8fc9e8',unlock:'Clear a dungeon without dying',owned:false},
    {id:'void',name:'Void Pilgrim',color:'#bb9be5',unlock:'Win 5 duel rounds',owned:false},
    {id:'gold',name:'Vault Gilded',color:'#e4c36f',unlock:'Open 25 vaults',owned:false},
    {id:'creator',name:'Dungeon Heart',color:'#ec719c',unlock:'Publish 5 dungeons',owned:false}
  ];
  const defaults={skin:'moss',publishedIds:[],stats:{bosses:0,clears:0,duelWins:0,vaults:0,published:0},settings:{reducedMotion:false,uiScale:100,colorMode:'default',volume:70,subtitles:true}};
  let meta;
  try{meta={...defaults,...JSON.parse(localStorage.getItem(SAVE)||'{}')};meta.stats={...defaults.stats,...meta.stats};meta.settings={...defaults.settings,...meta.settings};}catch{meta=structuredClone(defaults);}
  const save=()=>localStorage.setItem(SAVE,JSON.stringify(meta));
  const unlocks=()=>{for(const s of skins){s.owned=s.owned||(s.id==='ember'&&meta.stats.bosses>0)||(s.id==='frost'&&meta.stats.clears>0)||(s.id==='void'&&meta.stats.duelWins>=5)||(s.id==='gold'&&meta.stats.vaults>=25)||(s.id==='creator'&&meta.stats.published>=5);}};
  function applySettings(){document.documentElement.style.fontSize=`${meta.settings.uiScale}%`;document.body.classList.toggle('reduce-motion',meta.settings.reducedMotion);document.body.dataset.colorMode=meta.settings.colorMode;}
  applySettings();unlocks();
  const modal=$('frontModal'),body=$('frontBody');$('frontClose').onclick=()=>modal.close();
  function open(title,kicker='ONE MORE RELIC'){body.replaceChildren();const eyebrow=document.createElement('span');eyebrow.className='eyebrow';eyebrow.textContent=kicker;const h=document.createElement('h2');h.textContent=title;body.append(eyebrow,h);modal.showModal();return body;}
  const p=(parent,text)=>{const el=document.createElement('p');el.className='modal-copy';el.textContent=text;parent.append(el);return el;};
  const btn=(parent,text,fn,cls='subtle')=>{const b=document.createElement('button');b.className=cls;b.textContent=text;b.onclick=fn;parent.append(b);return b;};
  function enterGame(){modal.close();$('titleScreen').classList.add('gone');setTimeout(()=>$('titleScreen').classList.add('hidden'),500);}
  function roomUI(mode='dungeon'){
    const root=open(mode==='duel'?'Enter the rolling arena.':'Gather at the dungeon door.',mode==='duel'?'DUEL PLAYLIST · 2–4 PLAYERS':'CO-OP DUNGEON · 1–8 PLAYERS');
    p(root,mode==='duel'?'Stay with the same group as ten handcrafted arenas rotate. Every round resets temporary power.':'Create a private room, enter a friend’s code, or start solo. Party scaling adds enemy variety and boss mechanics.');
    const form=document.createElement('div');form.className='join-form';form.innerHTML='<label>NICKNAME<input id="joinName" maxlength="20" value="Wanderer"></label><label>ROOM CODE (OPTIONAL)<input id="joinCode" maxlength="5" placeholder="ABCDE"></label>';root.append(form);
    const actions=document.createElement('div');actions.className='modal-actions';root.append(actions);
    btn(actions,'Create / join room',()=>joinRoom(mode,false),'primary');btn(actions,'Play solo',()=>{enterGame();window.dispatchEvent(new CustomEvent('omr:mode',{detail:{mode,solo:true}}));});if(mode==='dungeon')btn(actions,'Rolling duels',()=>roomUI('duel'));
  }
  function joinRoom(mode,quickplay){
    if(!window.io){$('serverStatus').textContent='SERVER OFFLINE · SOLO AVAILABLE';if(!quickplay)enterGame();return;}
    const socket=window.__omrSocket ||= window.io(serverUrl);const name=$('joinName')?.value||'Wanderer',code=$('joinCode')?.value||'';
    socket.emit('room:join',{mode,name,code:code.trim().toUpperCase()||undefined,skin:meta.skin,quickplay},reply=>{
      if(!reply?.ok){alert(reply?.error||'Could not join');return;}
      $('roomCode').textContent=`ROOM ${reply.code}`;$('roomCode').classList.remove('hidden');showLobby(socket,mode,reply.code,reply.playerId);
    });
  }
  function showLobby(socket,mode,code,playerId){
    let state=null,launched=false;const root=open(code,mode==='duel'?'DUEL LOBBY · 2–4 PLAYERS':'DUNGEON LOBBY · 1–8 PLAYERS'),copy=p(root,'Waiting for party state…'),list=document.createElement('div'),actions=document.createElement('div');list.className='lobby-list';actions.className='modal-actions';root.append(list,actions);const start=btn(actions,'Start run',()=>socket.emit('room:start',reply=>{if(reply&&!reply.ok)copy.textContent=reply.error;}),'primary');btn(actions,'Leave',()=>{socket.disconnect();location.reload();});
    const render=room=>{state=room;window.OMRV11.room={...room,playerId,socket};list.replaceChildren();for(const player of Object.values(room.players)){const row=document.createElement('div');row.className='preset';row.innerHTML=`<div><strong>${player.name}</strong><small>${player.id===room.hostId?'HOST · ':''}${player.skin.toUpperCase()}</small></div><b>${player.connected?'READY':'AWAY'}</b>`;list.append(row);}start.hidden=room.hostId!==playerId;copy.textContent=mode==='duel'&&Object.keys(room.players).length<2?'Duels need at least two players. Share the room code.':`${Object.keys(room.players).length} player${Object.keys(room.players).length===1?'':'s'} connected.`;if(room.status==='playing'&&!launched){launched=true;enterGame();window.OMRV11.partySize=Object.keys(room.players).length;window.dispatchEvent(new CustomEvent('omr:room',{detail:{socket,mode,code,playerId,room}}));}if(room.status==='playing')window.dispatchEvent(new CustomEvent('omr:networkState',{detail:{...room,playerId}}));};
    socket.off('room:state');socket.on('room:state',render);
  }
  function quickplay(){const root=open('Choose your trouble.','QUICKPLAY');p(root,'Jump into the most active matching session. If none exists, a new public room starts immediately.');const actions=document.createElement('div');actions.className='quick-grid';root.append(actions);btn(actions,'QUICKPLAY DUNGEON',()=>{const input=document.createElement('input');input.id='joinName';input.value='Wanderer';input.hidden=true;body.append(input);joinRoom('dungeon',true);},'primary');btn(actions,'QUICKPLAY DUEL',()=>{const input=document.createElement('input');input.id='joinName';input.value='Wanderer';input.hidden=true;body.append(input);joinRoom('duel',true);},'primary');}
  function skinMenu(){const root=open('Wear your victories.','COSMETIC SKINS · NO GAMEPLAY ADVANTAGE');p(root,'Preview character colors now. Weapon, lantern, dash, death, and victory effects use the same cosmetic inventory model and can be expanded without changing combat data.');const grid=document.createElement('div');grid.className='skin-grid';root.append(grid);unlocks();for(const skin of skins){const card=document.createElement('button');card.className=`skin-card ${skin.id===meta.skin?'equipped':''}`;card.disabled=!skin.owned;card.innerHTML=`<i style="--skin:${skin.color}"></i><strong>${skin.name}</strong><small>${skin.owned?(skin.id===meta.skin?'EQUIPPED':'OWNED'):skin.unlock}</small>`;card.onclick=()=>{meta.skin=skin.id;save();skinMenu();window.dispatchEvent(new CustomEvent('omr:skin',{detail:skin}));};grid.append(card);}}
  function settings(){const root=open('Make the dungeon comfortable.','SETTINGS & ACCESSIBILITY');const form=document.createElement('div');form.className='settings-grid';form.innerHTML=`<label>UI SCALE<input id="uiScale" type="range" min="85" max="130" value="${meta.settings.uiScale}"><output>${meta.settings.uiScale}%</output></label><label>VOLUME<input id="volume" type="range" min="0" max="100" value="${meta.settings.volume}"><output>${meta.settings.volume}%</output></label><label>COLOR MODE<select id="colorMode"><option value="default">Default</option><option value="deuteranopia">Green / red assist</option><option value="tritanopia">Blue / yellow assist</option><option value="high">High contrast</option></select></label><label class="check"><input id="reducedMotion" type="checkbox" ${meta.settings.reducedMotion?'checked':''}> Reduced motion</label><label class="check"><input id="subtitles" type="checkbox" ${meta.settings.subtitles?'checked':''}> Subtitles</label>`;root.append(form);$('colorMode').value=meta.settings.colorMode;for(const id of ['uiScale','volume'])$(id).oninput=e=>{meta.settings[id]=Number(e.target.value);e.target.nextElementSibling.textContent=`${e.target.value}%`;save();applySettings();};for(const id of ['reducedMotion','subtitles'])$(id).onchange=e=>{meta.settings[id]=e.target.checked;save();applySettings();};$('colorMode').onchange=e=>{meta.settings.colorMode=e.target.value;save();applySettings();};}
  document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{const menu=b.dataset.menu;if(menu==='play')roomUI('dungeon');if(menu==='quickplay')quickplay();if(menu==='creator'){enterGame();setTimeout(()=>$('editorOpen').click(),50);}if(menu==='loadouts'){enterGame();setTimeout(()=>$('presetsOpen').click(),50);}if(menu==='skins')skinMenu();if(menu==='settings')settings();});
  window.addEventListener('omr:achievement',e=>{const key=e.detail?.key,amount=Math.max(1,Number(e.detail?.amount)||1);if(key==='published'&&e.detail?.id){meta.publishedIds=Array.isArray(meta.publishedIds)?meta.publishedIds:[];if(meta.publishedIds.includes(e.detail.id))return;meta.publishedIds.push(e.detail.id);}if(Object.hasOwn(meta.stats,key)){meta.stats[key]+=amount;unlocks();save();}});
  // Animated, deterministic menu vignette rendered without external art.
  const canvas=$('titleCanvas'),ctx=canvas.getContext('2d');let last=0;
  function titleFrame(now){const dpr=Math.min(devicePixelRatio,2),w=innerWidth,h=innerHeight;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#08100c';ctx.fillRect(0,0,w,h);const t=now/1000;for(let y=0;y<h;y+=48)for(let x=0;x<w;x+=48){ctx.fillStyle=((x/48+y/48)%2?'#15231a':'#18271d');ctx.fillRect(x,y,47,47);if((x*7+y*11)%17===0){ctx.fillStyle='#31432e';ctx.fillRect(x+8,y+32,18,2);}}for(let i=0;i<16;i++){const x=(w*.5+i*137)%w,y=(h*.18+i*83)%h;ctx.fillStyle='#3d513a';ctx.fillRect(x,y,42,42);}const px=w*.68+Math.cos(t*.5)*110,py=h*.52+Math.sin(t*.7)*70;const glow=ctx.createRadialGradient(px,py,10,px,py,230);glow.addColorStop(0,'#d9f3a888');glow.addColorStop(1,'#0000');ctx.fillStyle=glow;ctx.fillRect(px-230,py-230,460,460);ctx.fillStyle='#cde6a4';ctx.beginPath();ctx.arc(px,py,16,0,Math.PI*2);ctx.fill();for(let i=0;i<7;i++){const a=t*.6+i*Math.PI*2/7,r=45+i*4;ctx.fillStyle=['#e6b36e','#9cd4ce','#c69fe0'][i%3];ctx.beginPath();ctx.arc(px+Math.cos(a)*r,py+Math.sin(a)*r,5,0,Math.PI*2);ctx.fill();}const bx=w*.82,by=h*.55;ctx.fillStyle='#9073a3';ctx.fillRect(bx-28,by-28,56,56);ctx.fillStyle='#f1dc9e';ctx.fillRect(bx-12,by-5,7,7);ctx.fillRect(bx+5,by-5,7,7);last=now;requestAnimationFrame(titleFrame);}requestAnimationFrame(titleFrame);
  if(window.io){const s=window.io(serverUrl,{autoConnect:false});s.on('connect',()=>{$('serverStatus').textContent='MULTIPLAYER SERVER READY';s.disconnect();});s.on('connect_error',()=>{$('serverStatus').textContent='LOCAL MODE READY';});s.connect();}
  window.OMRV11={meta,skins,enterGame,roomUI,quickplay};
})();
